main: com.mortuusterra.MortuusTerraMain
name: MortuusTerra
version: 0.1
author: Kadeska23
depends: []
softdepends: []
database: false
description: Plugin for Mortuus Terra 
commands:
  channel:
    description: Base command for sellecting a chat channel
    usage: /channel
  mortuusterra:
    description: Base command for mortuusterra
    usage: /mortuusterra
